In [2]:
import pandas as pd

In [5]:
csv = "../raw_data/FM 2023.csv"

df = pd.read_csv(csv)

In [6]:
df.head()

,Name,Position,Age,ca,pa,Nationality,Club,Corners,Crossing,Dribbling,...,World reputation,Race,RCA,Colour of skin,Date of birth,Number of national team appearances,Goals scored for the national team,Salary,Rental club,UID
0,Kevin De Bruyne,M/AM RLC,31,189,189,Belgium,Manchester City,14,19,15,...,9400,Northern_European,181,4,1991/6/28,91,24,394372.0,NaN,18004457
1,Kylian Mbappé,AM/S RL,23,188,197,France,Paris Saint-Germain,13,13,18,...,9248,African_Caribbean,172,13,1998/12/20,57,27,1035616.0,NaN,85139014
2,Robert Lewandowski,S,33,186,190,Poland,Barcelona,3,8,13,...,9250,Northern_European,183,3,1988/8/21,132,76,345204.0,NaN,719601
3,Erling Haaland,S,22,185,195,"Norway,England",Manchester City,7,10,14,...,8750,Northern_European,185,2,2000/7/21,21,20,394372.0,NaN,29179241
4,Mohamed Salah,AM/S RL,30,185,187,Egypt,Liverpool,12,14,17,...,8750,North_African__Middle_Eastern,181,9,1992/6/15,85,47,405971.0,NaN,98028755

In [15]:
# X = df[['Name'],['Position'],['Age'],['Rental Club'],['Club'],['Corners'],["Crossing"],["Dribbling"],['Finishing'],['First Touch'],['Free Kick Taking'],['Heading'],['Long Shots'],['Long Throws'],['Marking'],['Passing'],['Penalty'],['Taking'],['Tackling'],['Technique'],['Aggressiion'],['Anticipation'],['Bravery'],['Composure'],['Concentration'],['Vision'],['Decision'],['Determination'],['Flair'],['Leadership'],['Off The Ball'],['Position'],['Teamwork'],['Work Rate'],['Acceleration'],['Agility'],['Balance'],['Jumping'],['Reach'],['Natural Fitness'],['Pace'],['Stamina'],['Strength'],['Stability'],['Foul'],['Contest performance'],['Injury'],['diversity'],['Aerial Reach'],['Command Of Area'],['Communication'],['Eccentricity'],['Handling'],['Kicking'],['One On Ones'],['Reflexes'],['Rushing Out'],['Punching'],['Throwing'],['Adaptation'],['Ambition'],['Argue'],['Loyal'],['Resistant to stress'],['Professional'],['Sportsmanship'],['Emotional control']]

new_df = df[['Name','Position','Age','Rental club','Club','Corners',"Crossing","Dribbling",'Finishing','First Touch','Free Kick Taking','Heading','Long Shots','Long Throws','Marking','Passing','Penalty Taking','Tackling','Technique','Aggressiion','Anticipation','Bravery','Composure','Concentration','Vision','Decision','Determination','Flair','Leadership','Off The Ball','Position','Teamwork','Work Rate','Acceleration','Agility','Balance','Jumping Reach','Natural Fitness','Pace','Stamina','Strength','Stability','Foul','Contest performance','Injury','diversity','Aerial Reach','Command Of Area','Communication','Eccentricity','Handling','Kicking','One On Ones','Reflexes','Rushing Out','Punching','Throwing','Adaptation','Ambition','Argue','Loyal','Resistant to stress','Professional','Sportsmanship','Emotional control',"Height",'Weight']].copy()

In [16]:
new_df

,Name,Position,Age,Rental club,Club,Corners,Crossing,Dribbling,Finishing,First Touch,...,Adaptation,Ambition,Argue,Loyal,Resistant to stress,Professional,Sportsmanship,Emotional control,Height,Weight
0,Kevin De Bruyne,M/AM RLC,31,NaN,Manchester City,14,19,15,16,16,...,13,17,13,14,11,18,16,13,181,68
1,Kylian Mbappé,AM/S RL,23,NaN,Paris Saint-Germain,13,13,18,17,18,...,15,20,8,14,16,16,12,13,178,73
2,Robert Lewandowski,S,33,NaN,Barcelona,3,8,13,19,18,...,15,20,15,10,16,18,10,11,185,81
3,Erling Haaland,S,22,NaN,Manchester City,7,10,14,18,16,...,16,20,12,15,18,17,10,12,195,88
4,Mohamed Salah,AM/S RL,30,NaN,Liverpool,12,14,17,17,17,...,16,19,8,13,16,18,16,17,175,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8447,Joe Ashton,D L,16,NaN,Burnley,3,4,5,4,4,...,14,12,1,9,11,11,11,20,181,0
8448,River Ries,S,17,NaN,Karlsruher SC,2,2,11,11,11,...,20,13,4,10,10,11,11,19,184,0
8449,Halilcan Doğan,D C,23,NaN,Osmaniyespor Futbol Kulübü,1,1,1,2,4,...,18,10,6,12,9,13,11,10,190,0
8450,Adijat Sefer,S,17,NaN,TSG Hoffenheim,3,4,12,7,8,...,20,12,8,12,11,9,11,20,184,0
8451,Linus Urban,S,17,NaN,SV Werder Bremen,4,2,10,13,8,...,19,13,7,12,10,12,11,11,174,0

In [14]:
header_names = []
for col in new_df.columns:
    header_names.append(col)
header_names

['Name',
 'Position',
 'Age',
 'Rental club',
 'Club',
 'Corners',
 'Crossing',
 'Dribbling',
 'Finishing',
 'First Touch',
 'Free Kick Taking',
 'Heading',
 'Long Shots',
 'Long Throws',
 'Marking',
 'Passing',
 'Penalty Taking',
 'Tackling',
 'Technique',
 'Aggressiion',
 'Anticipation',
 'Bravery',
 'Composure',
 'Concentration',
 'Vision',
 'Decision',
 'Determination',
 'Flair',
 'Leadership',
 'Off The Ball',
 'Position',
 'Teamwork',
 'Work Rate',
 'Acceleration',
 'Agility',
 'Balance',
 'Jumping Reach',
 'Natural Fitness',
 'Pace',
 'Stamina',
 'Strength',
 'Stability',
 'Foul',
 'Contest performance',
 'Injury',
 'diversity',
 'Aerial Reach',
 'Command Of Area',
 'Communication',
 'Eccentricity',
 'Handling',
 'Kicking',
 'One On Ones',
 'Reflexes',
 'Rushing Out',
 'Punching',
 'Throwing',
 'Adaptation',
 'Ambition',
 'Argue',
 'Loyal',
 'Resistant to stress',
 'Professional',
 'Sportsmanship',
 'Emotional control']