In [2]:
#imports

import pandas as pd

In [ ]:
#read CSVs

In [5]:
attributes = pd.read_csv("../raw_data/FM 2023.csv")

In [7]:
player_info = pd.read_csv("../raw_data/player_info.csv")

In [13]:
lineups = pd.read_json("../raw_data/epl_2022_2023_07_02_2023.json")

In [9]:
attributes.head(5)

,Name,Position,Age,ca,pa,Nationality,Club,Corners,Crossing,Dribbling,...,World reputation,Race,RCA,Colour of skin,Date of birth,Number of national team appearances,Goals scored for the national team,Salary,Rental club,UID
0,Kevin De Bruyne,M/AM RLC,31,189,189,Belgium,Manchester City,14,19,15,...,9400,Northern_European,181,4,1991/6/28,91,24,394372.0,NaN,18004457
1,Kylian Mbappé,AM/S RL,23,188,197,France,Paris Saint-Germain,13,13,18,...,9248,African_Caribbean,172,13,1998/12/20,57,27,1035616.0,NaN,85139014
2,Robert Lewandowski,S,33,186,190,Poland,Barcelona,3,8,13,...,9250,Northern_European,183,3,1988/8/21,132,76,345204.0,NaN,719601
3,Erling Haaland,S,22,185,195,"Norway,England",Manchester City,7,10,14,...,8750,Northern_European,185,2,2000/7/21,21,20,394372.0,NaN,29179241
4,Mohamed Salah,AM/S RL,30,185,187,Egypt,Liverpool,12,14,17,...,8750,North_African__Middle_Eastern,181,9,1992/6/15,85,47,405971.0,NaN,98028755

In [11]:
player_info.head(5)

   Unnamed: 0       player_name             team    birthday position
0           0  Daniel Adu-Adjei  AFC Bournemouth  21/06/2005       FW
1           1    Jaidon Anthony  AFC Bournemouth  01/12/1999       FW
2           2    Philip Billing  AFC Bournemouth  11/06/1996       MF
3           3      David Brooks  AFC Bournemouth  08/07/1997       FW
4           4     Ryan Christie  AFC Bournemouth  22/02/1995       MF

In [20]:
lineups.head(5)

,event,matchweek,team1_name,team1_startings,team1_subs,team1_stat,team2_name,team2_startings,team2_subs,team2_stat
75091,"[Full-time Match ends, Arsenal 0, Newcastle Un...",Matchweek 19,Arsenal,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Matt Turner, Kieran Tierney, Rob Holding, Tak...","{'possession_%': '66.8', 'shots_on_target': '4...",Newcastle United,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...","{'possession_%': '33.2', 'shots_on_target': '1..."
75096,"[Full-time Match ends, Everton 1, Brighton and...",Matchweek 19,Everton,"[Jordan Pickford, James Tarkowski, Nathan Patt...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...","{'possession_%': '48.9', 'shots_on_target': '4...",Brighton and Hove Albion,"[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...","{'possession_%': '51.1', 'shots_on_target': '8..."
75098,"[Full-time Match ends, Leicester City 0, Fulha...",Matchweek 19,Leicester City,"[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...","{'possession_%': '61.2', 'shots_on_target': '6...",Fulham,"[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...","{'possession_%': '38.8', 'shots_on_target': '2..."
75099,"[Full-time Match ends, Manchester United 3, Bo...",Matchweek 19,Manchester United,"[David de Gea, Victor Lindelöf, Harry Maguire,...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...","{'possession_%': '58.5', 'shots_on_target': '6...",Bournemouth,"[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...","{'possession_%': '41.5', 'shots_on_target': '4..."
75093,"[Full-time Match ends, Brentford 3, Liverpool ...",Matchweek 19,Brentford,"[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...","{'possession_%': '27', 'shots_on_target': '7',...",Liverpool,"[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...","{'possession_%': '73', 'shots_on_target': '6',..."

In [19]:
lineups = lineups.transpose()

In [25]:
lineups['match'] = lineups['team1_name'] + ' v ' + lineups['team2_name']

In [26]:
lineups.head(5)

,event,matchweek,team1_name,team1_startings,team1_subs,team1_stat,team2_name,team2_startings,team2_subs,team2_stat,match
75091,"[Full-time Match ends, Arsenal 0, Newcastle Un...",Matchweek 19,Arsenal,"[Aaron Ramsdale, Ben White, Gabriel Magalhães,...","[Matt Turner, Kieran Tierney, Rob Holding, Tak...","{'possession_%': '66.8', 'shots_on_target': '4...",Newcastle United,"[Nick Pope, Kieran Trippier, Sven Botman, Fabi...","[Martin Dúbravka, Jamaal Lascelles, Jamal Lewi...","{'possession_%': '33.2', 'shots_on_target': '1...",Arsenal v Newcastle United
75096,"[Full-time Match ends, Everton 1, Brighton and...",Matchweek 19,Everton,"[Jordan Pickford, James Tarkowski, Nathan Patt...","[Asmir Begovic, Yerry Mina, Ben Godfrey, Séamu...","{'possession_%': '48.9', 'shots_on_target': '4...",Brighton and Hove Albion,"[Robert Sánchez, Lewis Dunk, Levi Colwill, Per...","[Jason Steele, Tariq Lamptey, Jan Paul van Hec...","{'possession_%': '51.1', 'shots_on_target': '8...",Everton v Brighton and Hove Albion
75098,"[Full-time Match ends, Leicester City 0, Fulha...",Matchweek 19,Leicester City,"[Danny Ward, Wout Faes, Daniel Amartey, Timoth...","[Daniel Iversen, Çaglar Söyüncü, Jannik Vester...","{'possession_%': '61.2', 'shots_on_target': '6...",Fulham,"[Bernd Leno, Kenny Tete, Tosin Adarabioyo, Tim...","[Marek Rodák, Layvin Kurzawa, Issa Diop, Harry...","{'possession_%': '38.8', 'shots_on_target': '2...",Leicester City v Fulham
75099,"[Full-time Match ends, Manchester United 3, Bo...",Matchweek 19,Manchester United,"[David de Gea, Victor Lindelöf, Harry Maguire,...","[Tom Heaton, Lisandro Martínez, Tyrell Malacia...","{'possession_%': '58.5', 'shots_on_target': '6...",Bournemouth,"[Mark Travers, Lloyd Kelly, Chris Mepham, Adam...","[Cameron Plain, Jack Stephens, Jack Stacey, Jo...","{'possession_%': '41.5', 'shots_on_target': '4...",Manchester United v Bournemouth
75093,"[Full-time Match ends, Brentford 3, Liverpool ...",Matchweek 19,Brentford,"[David Raya, Ethan Pinnock, Zanka, Ben Mee, Ri...","[Thomas Strakosha, Mads Bech Sørensen, Tristan...","{'possession_%': '27', 'shots_on_target': '7',...",Liverpool,"[Alisson, Virgil van Dijk, Ibrahima Konaté, Ko...","[Caoimhín Kelleher, Joe Gomez, Andrew Robertso...","{'possession_%': '73', 'shots_on_target': '6',...",Brentford v Liverpool

In [33]:
test = lineups.query("team1_name == 'Manchester City'")

In [36]:
test['team1_startings'][75085]

['Ederson',
 'John Stones',
 'Nathan Aké',
 'Manuel Akanji',
 'Rico Lewis',
 'Rodri',
 'Kevin De Bruyne',
 'Bernardo Silva',
 'Erling Haaland',
 'Jack Grealish',
 'Riyad Mahrez']